/**
 * Statistics engine for administrators — the sole AI-branded feature in
 * MediConnect. It runs real aggregate SQL over the platform's own data
 * (never patient-identifying detail) and turns the results into short,
 * plain-language insights, generated by Gemini when configured. This is
 * intentionally the only AI surface in the system: there is no AI-generated
 * clinical suggestion shown to doctors — diagnosis and treatment decisions
 * are the clinician's alone.
 *
 * If GEMINI_API_KEY is unset, or the call fails for any reason (network,
 * quota, bad response shape), this silently falls back to the original
 * rule-based summaries below rather than breaking the admin dashboard —
 * same "degrade gracefully" pattern as email and payments elsewhere in
 * this codebase.
 */

const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-2.5-flash";

// Google issues two kinds of keys: AI Studio keys ("AIza...") for the Gemini
// Developer API, and Vertex AI express-mode keys ("AQ....") which are rejected
// by the Developer API endpoint and must go to the Vertex endpoint instead.
function geminiUrl() {
  const key = process.env.GEMINI_API_KEY || "";
  return key.startsWith("AQ.")
    ? `https://aiplatform.googleapis.com/v1/publishers/google/models/${GEMINI_MODEL}:generateContent`
    : `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`;
}

function ruleBasedInsights({ specialtyDemand, appointmentTrend, doctorWorkload, conditionFrequency }) {
  const insights = [];

  if (specialtyDemand.length > 0) {
    const top = specialtyDemand[0];
    insights.push(`"${top.specialty}" is currently the most requested specialty, with ${top.count} appointment(s).`);
    const underused = specialtyDemand[specialtyDemand.length - 1];
    if (specialtyDemand.length > 1 && underused.count === 0) {
      insights.push(`"${underused.specialty}" has received no appointment requests yet — consider reviewing coverage or promotion for this specialty.`);
    }
  }

  const overloaded = doctorWorkload.filter((d) => d.appointment_count >= 8);
  if (overloaded.length > 0) {
    insights.push(`${overloaded.length} doctor(s) have a high current workload (8+ scheduled appointments) — additional support may be needed: ${overloaded.map((d) => d.name).join(", ")}.`);
  }

  if (appointmentTrend.length >= 2) {
    const last = appointmentTrend[appointmentTrend.length - 1];
    const prev = appointmentTrend[appointmentTrend.length - 2];
    if (last && prev && prev.count > 0) {
      const change = (((last.count - prev.count) / prev.count) * 100).toFixed(0);
      if (Math.abs(change) >= 10) {
        insights.push(`Appointment volume ${change > 0 ? "increased" : "decreased"} by ${Math.abs(change)}% from ${prev.month} to ${last.month}.`);
      }
    }
  }

  if (conditionFrequency.length > 0) {
    const top = conditionFrequency[0];
    insights.push(`The most frequently recorded diagnosis is "${top.diagnosis}" (${top.count} occurrence(s)).`);
  }

  if (insights.length === 0) {
    insights.push("Not enough data yet to identify meaningful trends — insights will improve as more appointments and consultations are recorded.");
  }

  return insights;
}

async function geminiInsights(stats) {
  if (!process.env.GEMINI_API_KEY) return null;

  const prompt = `You are summarizing operational statistics for the admin dashboard of a
healthcare booking platform called MediConnect. Below is aggregate data only —
no patient names or identifying detail. Write 2-4 short, plain-language
insights a clinic administrator would find useful (staffing gaps, demand
shifts, workload concerns). Return ONLY a JSON array of strings, no markdown,
no extra commentary.

Specialty demand: ${JSON.stringify(stats.specialtyDemand)}
Appointment trend (by month): ${JSON.stringify(stats.appointmentTrend)}
Doctor workload (open appointments): ${JSON.stringify(stats.doctorWorkload)}
Most frequent diagnoses: ${JSON.stringify(stats.conditionFrequency)}`;

  const res = await fetch(geminiUrl(), {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": process.env.GEMINI_API_KEY.trim() },
    body: JSON.stringify({
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      generationConfig: { responseMimeType: "application/json", thinkingConfig: { thinkingBudget: 0 } },
    }),
  });
  if (!res.ok) {
    const detail = (await res.text().catch(() => "")).slice(0, 300);
    throw new Error(`Gemini request failed with status ${res.status}: ${detail}`);
  }
  const data = await res.json();
  const text = (data?.candidates?.[0]?.content?.parts || []).map((p) => p.text || "").join("").trim();
  const parsed = JSON.parse(text.replace(/^```(?:json)?|```$/g, "").trim());
  if (!Array.isArray(parsed) || parsed.length === 0) throw new Error("Gemini returned an unexpected shape.");
  return parsed.map(String);
}

async function buildInsights(stats) {
  try {
    const fromGemini = await geminiInsights(stats);
    if (fromGemini) return { insights: fromGemini, source: "gemini" };
  } catch (err) {
    console.warn("Gemini insights failed, falling back to rule-based summaries:", err.message);
  }
  return { insights: ruleBasedInsights(stats), source: "rule-based" };
}

module.exports = { buildInsights };
